#!/bin/bash
leadname=$1
leadphone=$2
leademail=$3
property_address=$4
property_id=$5
mailto=$6
echo -e "you have a lead generated by Realestator.com:\n   name:$leadname\n   phone:$leadphone \n   propid:$property_id\n   address:$property_address\n   email:$leademail\n" | sendmail -F "realestator" -f "noreply@realestator.com" $mailto
#
# email install: 
#dfn install postfix
#mkfifo /var/spool/postfix/public/pickup
#service postfix restart
#
